name: investing
description: A Stock Watchlist App
publish_to: 'none'
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1


environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  material_design_icons_flutter: ^5.0.6996
  syncfusion_flutter_charts: ^20.2.39
  dropdown_search: ^5.0.2
  provider: ^6.0.3
  http: ^0.13.4
  flutter_secure_storage: ^5.0.2
  shimmer: ^2.0.0
  cloud_firestore: ^4.1.0

  #  Minimum requirement for firebase_auth is 'IOS: 10' on Xcode
  #  Xcode under "Runner" -> "Runner" -> "Info" -> "iOS Deployment Target" to version >= 10.0.0
  firebase_auth: ^4.1.0
  firebase_core: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
          weight: 800
